FILENAME=MovieList.cpp
FLAGS=-std=c++11 -Wall -o
EXENAME=MovieList

QUEUEOBJECT=Queue.o
QUEUEHEADER=Queue.h
QUEUECLASS=Queue.cpp

MOVIEOBJECT=MovieHandler.o
MOVIEHEADER=MovieHandler.h
MOVIECLASS=MovieHandler.cpp

main: $(QUEUEOBJECT) $(MOVIEOBJECT)
	g++ $(FILENAME) $(FLAGS) $(EXENAME) $(QUEUEOBJECT) $(MOVIEOBJECT)

$(QUEUEOBJECT): $(STACKHEADER) $(STACKCLASS)
	g++ -c -std=c++11 -Wall $(QUEUECLASS)

$(MOVIEOBJECT): $(MOVIEHEADER) $(MOVIECLASS)
	g++ -c -std=c++11 -Wall $(MOVIECLASS)

clean:
	$(RM) 

